[versions]
kotlin = "2.4.10"
clikt = "5.1.0"
vannik = "0.37.0"
kover = "0.9.9"
kotlinx-io = "0.9.1"
bcv = "0.18.1"

[libraries]
clikt = { module = "com.github.ajalt.clikt:clikt", version.ref = "clikt"}
kotlinx-io-core = { module = "org.jetbrains.kotlinx:kotlinx-io-core", version.ref = "kotlinx-io"}

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
vannik-publish = { id = "com.vanniktech.maven.publish", version.ref = "vannik" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
bcv = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version.ref = "bcv" }
