name: Release build
on:
  release:
    types: [created]
  workflow_dispatch:
jobs:
  publish-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - id: install-secret-key
        name: Install gpg secret key
        run: |
          cat <(echo -e "${{ secrets.OSSRH_GPG_SECRET_KEY }}") | base64 -d | gpg --batch --import
          gpg --list-secret-keys --keyid-format LONG

      - name: Publish non-Apple targets
        run: >-
          ./gradlew
          -PmavenCentralUsername=${{ secrets.OSSRH_USERNAME }}
          -PmavenCentralPassword=${{ secrets.OSSRH_TOKEN }}
          -Psigning.gnupg.passphrase='${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}'
          :kcsg:publishJvmPublicationToMavenCentralRepository
          :kcsg:publishJsPublicationToMavenCentralRepository
          :kcsg:publishWasmJsPublicationToMavenCentralRepository
          :kcsg:publishWasmWasiPublicationToMavenCentralRepository
          :kcsg:publishLinuxX64PublicationToMavenCentralRepository
          :kcsg:publishLinuxArm64PublicationToMavenCentralRepository
          :kcsg:publishMingwX64PublicationToMavenCentralRepository
          :kcsg:publishKotlinMultiplatformPublicationToMavenCentralRepository
          :kcsg-dsl:publishJvmPublicationToMavenCentralRepository
          :kcsg-dsl:publishJsPublicationToMavenCentralRepository
          :kcsg-dsl:publishWasmJsPublicationToMavenCentralRepository
          :kcsg-dsl:publishWasmWasiPublicationToMavenCentralRepository
          :kcsg-dsl:publishLinuxX64PublicationToMavenCentralRepository
          :kcsg-dsl:publishLinuxArm64PublicationToMavenCentralRepository
          :kcsg-dsl:publishMingwX64PublicationToMavenCentralRepository
          :kcsg-dsl:publishKotlinMultiplatformPublicationToMavenCentralRepository
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}

  publish-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - id: install-secret-key
        name: Install gpg secret key
        run: |
          cat <(echo -e "${{ secrets.OSSRH_GPG_SECRET_KEY }}") | base64 -d | gpg --batch --import
          gpg --list-secret-keys --keyid-format LONG

      - name: Publish Apple targets
        run: >-
          ./gradlew
          -PmavenCentralUsername=${{ secrets.OSSRH_USERNAME }}
          -PmavenCentralPassword=${{ secrets.OSSRH_TOKEN }}
          -Psigning.gnupg.passphrase='${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}'
          :kcsg:publishIosArm64PublicationToMavenCentralRepository
          :kcsg:publishIosSimulatorArm64PublicationToMavenCentralRepository
          :kcsg:publishIosX64PublicationToMavenCentralRepository
          :kcsg:publishMacosArm64PublicationToMavenCentralRepository
          :kcsg:publishMacosX64PublicationToMavenCentralRepository
          :kcsg:publishTvosArm64PublicationToMavenCentralRepository
          :kcsg:publishTvosSimulatorArm64PublicationToMavenCentralRepository
          :kcsg:publishTvosX64PublicationToMavenCentralRepository
          :kcsg:publishWatchosArm32PublicationToMavenCentralRepository
          :kcsg:publishWatchosArm64PublicationToMavenCentralRepository
          :kcsg:publishWatchosSimulatorArm64PublicationToMavenCentralRepository
          :kcsg:publishWatchosX64PublicationToMavenCentralRepository
          :kcsg-dsl:publishIosArm64PublicationToMavenCentralRepository
          :kcsg-dsl:publishIosSimulatorArm64PublicationToMavenCentralRepository
          :kcsg-dsl:publishIosX64PublicationToMavenCentralRepository
          :kcsg-dsl:publishMacosArm64PublicationToMavenCentralRepository
          :kcsg-dsl:publishMacosX64PublicationToMavenCentralRepository
          :kcsg-dsl:publishTvosArm64PublicationToMavenCentralRepository
          :kcsg-dsl:publishTvosSimulatorArm64PublicationToMavenCentralRepository
          :kcsg-dsl:publishTvosX64PublicationToMavenCentralRepository
          :kcsg-dsl:publishWatchosArm32PublicationToMavenCentralRepository
          :kcsg-dsl:publishWatchosArm64PublicationToMavenCentralRepository
          :kcsg-dsl:publishWatchosSimulatorArm64PublicationToMavenCentralRepository
          :kcsg-dsl:publishWatchosX64PublicationToMavenCentralRepository
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}

  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - name: Build CSGS fat jar
        run: ./gradlew csgs:fatJar

      - name: Upload to release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            csgs/build/libs/csgs-all-*.jar
